name: GitHub Coverage Badge Action
description: Simple coverage badge that doesn't require external services or hosting, using just GitHub Actions.

branding:
  icon: check-circle
  color: green

inputs:
  label:
    description: "The label for the badge"
    required: false
    default: "coverage"
  coverage-summary-path:
    description: "The path to the coverage summary file"
    required: false
    default: "./coverage/coverage-summary.json"
  style:
    description: "The badge style, either 'github' or 'classic'"
    required: false
    default: "github"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - uses: ./node-action
      with:
        label: ${{ inputs.label }}
        coverage-summary-path: ${{ inputs.coverage-summary-path }}
        style: ${{ inputs.style }}

    - uses: actions/checkout@v4
      with:
        ref: gh-pages

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: gh-pages
        skip_fetch: true
        skip_checkout: true
        file_pattern: badges/**
        commit_message: "chore(badge): update coverage badge"
        commit_options: "--no-verify"

    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
