name: GitHub Coverage Badge
description: Coverage badge, no external services or hosting required.

branding:
  icon: check-circle
  color: green

inputs:
  label:
    description: 'The label for the badge'
    required: false
    default: 'coverage'

runs:
  using: composite
  steps:
    - name: get-values
      id: get-values
      shell: bash
      run: |
        COV=$(node -p 't=require(`./coverage/coverage-summary.json`).total,Math.min(...`lines|statements|functions|branches`.split(`|`).map(k=>t[k].pct))')
        echo "coverage=$COV" >> $GITHUB_OUTPUT

    - name: checkout
      uses: actions/checkout@v4
      with:
        ref: gh-pages

    - name: create-badge
      shell: bash
      run: |
        export COV=${{ steps.get-values.outputs.coverage }}
        COLOR=$(node -p '+process.env.COV >= 90 ? `brightgreen` : process.env.COV >= 80 ? `green` : process.env.COV >= 50 ? `orange` : `red`')
        mkdir -p badges
        npx --yes badge-maker@^4 "${{ inputs.label }}" "$COV%" :brightgreen > badges/coverage.svg

    - name: deploy-badge
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: gh-pages
        skip_fetch: true
        skip_checkout: true
        file_pattern: badges/**.svg
        commit_message: "chore: update coverage badge"
        commit_options: '--no-verify --signoff'

    - name: cleanup
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}