name: Test
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      # Install and Test Example
      - name: Install and Test Example
        run: |
          cd example
          npm install
          npm run test:cov
          cp -r coverage ..
          cd ..

      # Add this
      - name: Update Coverage Badge
        uses: ./
